### ISSUE TITLE
R Project Milestone 2 Tasks

### ISSUE THREAD

**Issue by cmmclaug** [UBC-MDS/aRidanalysis#1]
- [x] 1. Create project structure for R repo
     - [x] R project structure
     - [x] name related to package
     - [x] MIT license
     - [x] DESCRIPTION file.
     - [x] CONTRIBUTING.md
     - [x] usethis::use_code_of_conduct
     - [x] copy README.md containing:
          - [x] summary paragraph
          - [x] bulleted list of functions
          - [x] package fitting in R ecosystem
- [x] 2. R Function specifications
     - [x] Neel Function
     - [x] Craig Function
     - [x] Daniel Function
     - [x] Santiago Function
- [x] 3. R Project GitHub Mechanics
    - [x] Always add meaningful commit messages
    - [x] Use GitHub Flow workflow
    - [x] Manage GitHub issues for communication
    - [x] Verify use of proper grammar and full sentences throughout project.
