### ISSUE TITLE
R Project Milestone 3 Tasks 

### ISSUE THREAD

**Issue by nphaterp** [UBC-MDS/aRidanalysis#19]
**Submission**  
- [x] Create new Python release named v0.2.0
- [x] Create new R release named v0.1.0
- [x] Canvas submission (including repo url of public repo for R repo and Python Repo, url of release for R and Python)

**Checklist**
- [x] 1. Write test cases and code iteratively
    - [x] `arid_eda` function
        - [x] Revise function
        - [x] Write test function
        - [x] Write function
        - [x] Handles exceptions with suitable error messages
    - [x] `arid_linreg` function
        - [x] Revise function
        - [x] Write test function
        - [x] Write function
        - [x] Handles exceptions with suitable error messages
    - [x] `arid_logreg` function
        - [x] Revise function
        - [x] Write test function
        - [x] Write function 
        - [x] Handles exceptions with suitable error messages
    - [x] `arid_countreg` function
        - [x] Revise function
        - [x] Write test function
        - [x] Write function 
        - [x] Handles exceptions with suitable error messages
- [x] 2. Make sure all functions pass `testthat` package
- [x] 3. Exception handling
     - [x] Erroneous Inputs are handled for all functions
     - [x] Exceptions are tested and provide useful messages
- [x] 4. Verify package functions can be installed and used
-[ ] 5. Update Python Package
    - [x] Continuous Integration
     - [x] GitHub actions workflow for continuous deployment
     - [x] Update Documentation
- [x] 6. R Function specifications
     - [x] Neel Function
     - [x] Craig Function
     - [x] Daniel Function
     - [x] Santiago Function
- [x] 7. R Project GitHub Mechanics
    - [x] Always add meaningful commit messages
    - [x] Use GitHub Flow workflow
    - [x] Manage GitHub issues for communication
        - [x] Copy this task list or a subset over to R project
    - [x] Verify use of proper grammar and full sentences throughout project.
